service: spring-boot-serverless

provider:
  name: aws
  runtime: java11
  
package:
  artifact: build/distributions/springboot-serverless-0.0.1-SNAPSHOT.zip
  
functions:
  springBootServerless:
    handler: com.example.demo.LambdaHandler::handleRequest
    events:
      - http:
          path: /users
          method: get
    timeout: 30